//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_file_Excel.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_ThucTapEntities : DbContext
    {
        public Db_ThucTapEntities()
            : base("name=Db_ThucTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIABAN> DIABANs { get; set; }
        public virtual DbSet<HUYEN> HUYENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THANHVIENTRONGHO> THANHVIENTRONGHOes { get; set; }
        public virtual DbSet<THONGTINHO> THONGTINHOes { get; set; }
        public virtual DbSet<THONGTINTUVONG> THONGTINTUVONGs { get; set; }
        public virtual DbSet<TINH> TINHs { get; set; }
        public virtual DbSet<VUNG> VUNGs { get; set; }
        public virtual DbSet<XA> XAs { get; set; }
    }
}
