//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_file_Excel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhiNhan
    {
        public string ThongTin { get; set; }
        public System.DateTime Ngay { get; set; }
        public string NguoiDung { get; set; }
    }
}
