//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_file_Excel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIENTRONGHO
    {
        public string MaHo { get; set; }
        public string MaThanhVien { get; set; }
        public string STT { get; set; }
        public string HoTen { get; set; }
        public string C02 { get; set; }
        public string C03 { get; set; }
        public string C04T { get; set; }
        public string C04N { get; set; }
        public string C05 { get; set; }
        public string C06A { get; set; }
        public string C06B { get; set; }
        public string C06C { get; set; }
        public string C07 { get; set; }
        public string C08 { get; set; }
        public string C09 { get; set; }
        public string C09A { get; set; }
        public string C09B { get; set; }
        public string C10 { get; set; }
        public string C11A { get; set; }
        public string C11B { get; set; }
        public string C11C { get; set; }
        public string C11D { get; set; }
        public string C11E { get; set; }
        public string C11F { get; set; }
        public string C11FK { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C13A { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public string C16A { get; set; }
        public string C16B { get; set; }
        public string C16C { get; set; }
        public string C16D { get; set; }
        public string C16E { get; set; }
        public string C16F { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C19 { get; set; }
        public string C20A { get; set; }
        public string C20B { get; set; }
        public string C20C { get; set; }
        public string C20D { get; set; }
        public string C20E { get; set; }
        public string C21A { get; set; }
        public string C21B { get; set; }
        public string C21C { get; set; }
        public string C21D { get; set; }
        public string C21E { get; set; }
        public string C21F { get; set; }
        public string C21FK { get; set; }
        public string C22T { get; set; }
        public string C22N { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string C25A { get; set; }
        public string C25B { get; set; }
        public string C26A { get; set; }
        public string C26B { get; set; }
        public string C27A { get; set; }
        public string C27B { get; set; }
        public string C28A { get; set; }
        public string C28B { get; set; }
        public string C29T { get; set; }
        public string C29N { get; set; }
        public string C30A { get; set; }
        public string C30B { get; set; }
        public string C31 { get; set; }
        public string C31A { get; set; }
        public string C32 { get; set; }
        public string C33 { get; set; }
        public string C34 { get; set; }
        public string C34K { get; set; }
        public string C35 { get; set; }
        public string C36 { get; set; }
        public string C36K { get; set; }
        public string C37 { get; set; }
        public string C37K { get; set; }
        public string C38 { get; set; }
        public string C39 { get; set; }
        public string C40 { get; set; }
        public string C40K { get; set; }
        public string C41 { get; set; }
        public string C41K { get; set; }
        public string C42 { get; set; }
        public string C43 { get; set; }
        public string C43K { get; set; }
        public string C44 { get; set; }
        public string C44K { get; set; }
        public string C52 { get; set; }
        public string C53 { get; set; }
        public string C54 { get; set; }
        public string C55A { get; set; }
        public string C55B { get; set; }
        public string C55C { get; set; }
        public string C55D { get; set; }
        public string C55E { get; set; }
        public string C56A { get; set; }
        public string C56B { get; set; }
        public string C56C { get; set; }
        public string C56D { get; set; }
        public string C56E { get; set; }
        public string C57 { get; set; }
        public string C58A { get; set; }
        public string C58B { get; set; }
        public string C58C { get; set; }
        public string C58D { get; set; }
        public string C58E { get; set; }
        public string C58F { get; set; }
        public string C58G { get; set; }
        public string C58H { get; set; }
        public string C58I { get; set; }
        public string C58J { get; set; }
        public string C58K { get; set; }
        public string C58KK { get; set; }
        public string C59 { get; set; }
        public string C60 { get; set; }
        public string C61 { get; set; }
        public string C62 { get; set; }
        public string C63 { get; set; }
    
        public virtual THONGTINHO THONGTINHO { get; set; }
    }
}
