//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_file_Excel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINTUVONG
    {
        public string MaHo { get; set; }
        public string MaTVong { get; set; }
        public string STTTV { get; set; }
        public string HoTenTV { get; set; }
        public bool GioiTinh { get; set; }
        public string ThangTV { get; set; }
        public string NamTV { get; set; }
        public string ThangSinh { get; set; }
        public string NamSinh { get; set; }
        public string Tuoi { get; set; }
        public string NguyenNhan { get; set; }
    
        public virtual THONGTINHO THONGTINHO { get; set; }
    }
}
