//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_file_Excel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class XA
    {
        public string MaXa { get; set; }
        public string MaHuyen { get; set; }
        public string MaTinh { get; set; }
        public string TenXa { get; set; }
    
        public virtual HUYEN HUYEN { get; set; }
        public virtual TINH TINH { get; set; }
    }
}
